# Generated by Django 6.0.5 on 2026-06-02 17:40

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='TiposCafe',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre_cliente', models.CharField(max_length=200)),
                ('correo_electronico', models.EmailField(max_length=200)),
                ('telefono_contacto', models.CharField(max_length=20)),
                ('tipo_cafe_preferido', models.CharField(max_length=100)),
                ('tamano_bebida', models.CharField(max_length=50)),
                ('nivel_intensidad', models.CharField(max_length=50)),
                ('tipo_leche', models.CharField(max_length=100)),
                ('comentarios', models.TextField(blank=True, null=True)),
                ('fecha_hora_pedido', models.DateTimeField()),
            ],
        ),
    ]
